import {
  LayoutDashboard,
  Users,
  Package,
  Contact,
  Truck,
  ShoppingCart,
  Warehouse,
  Factory,
  ShoppingBag,
  Wallet,
  Bell,
  FileBarChart,
  Undo2,
  CalendarCheck,
  Boxes,
  Wrench,
} from 'lucide-react';
import { MODULES } from '@/constants/roles';

export const NAV_ITEMS = [
  { module: MODULES.DASHBOARD, label: 'Dashboard', to: '/dashboard', icon: LayoutDashboard },
  { module: MODULES.ATTENDANCE, label: 'Attendance', to: '/attendance', icon: CalendarCheck },
  {
    module: MODULES.PRODUCTS,
    label: 'Products',
    to: '/products',
    icon: Package,
    children: [
      { key: 'products', label: 'Products' },
      { key: 'categories', label: 'Categories' },
      { key: 'brands', label: 'Brands' },
      { key: 'variants', label: 'Variants' },
    ],
  },
  {
    module: MODULES.CUSTOMERS,
    label: 'Customers',
    to: '/customers',
    icon: Contact,
    children: [
      { key: 'customers', label: 'Customers' },
      { key: 'communications', label: 'Communication History' },
    ],
  },
  { module: MODULES.VENDORS, label: 'Vendors', to: '/vendors', icon: Truck },
  {
    module: MODULES.PURCHASES,
    label: 'Purchases',
    to: '/purchases',
    icon: ShoppingCart,
    children: [
      { key: 'requests', label: 'Purchase Requests' },
      { key: 'rfqs', label: 'RFQ & Quotations' },
      { key: 'purchases', label: 'Purchase Orders' },
      { key: 'grn', label: 'Goods Receipt Notes' },
    ],
  },
  {
    module: MODULES.INVENTORY,
    label: 'Inventory',
    to: '/inventory',
    icon: Warehouse,
    children: [
      { key: 'inventory', label: 'Inventory' },
      { key: 'zones', label: 'Zones' },
      { key: 'racks', label: 'Racks' },
      { key: 'shelves', label: 'Shelves' },
      { key: 'bins', label: 'Bins' },
      { key: 'movements', label: 'Movements' },
      { key: 'materialIssue', label: 'Material Issue' },
    ],
  },
  {
    module: MODULES.ITEM_MASTER,
    label: 'Item Master',
    to: '/item-master',
    icon: Boxes,
    children: [
      { key: 'categories', label: 'Categories' },
      { key: 'items', label: 'Items' },
      { key: 'variants', label: 'Variants' },
      { key: 'stock', label: 'Stock' },
      { key: 'movements', label: 'Stock Movements' },
    ],
  },
  {
    module: MODULES.PRODUCTION,
    label: 'Production',
    to: '/production',
    icon: Factory,
    children: [
      { key: 'workOrders', label: 'Work Orders' },
      { key: 'materialRequests', label: 'Material Requests' },
      { key: 'bom', label: 'Bill of Materials' },
      { key: 'machines', label: 'Machines' },
    ],
  },
  {
    module: MODULES.FIXED_ASSETS,
    label: 'Fixed Assets',
    to: '/fixed-assets',
    icon: Wrench,
    children: [
      { key: 'register', label: 'Asset Register' },
      { key: 'maintenance', label: 'Maintenance Logs' },
    ],
  },
  { module: MODULES.SALES, label: 'Sales', to: '/sales', icon: ShoppingBag },
  {
    module: MODULES.FINANCE,
    label: 'Finance',
    to: '/finance',
    icon: Wallet,
    children: [
      { key: 'invoices', label: 'Invoices' },
      { key: 'payments', label: 'Customer Payments' },
      { key: 'vendorBills', label: 'Vendor Bills' },
      { key: 'approvals', label: 'Approval Queue' },
      { key: 'creditNotes', label: 'Credit Notes' },
      { key: 'loanRequests', label: 'Loan Requests' },
      { key: 'loans', label: 'Loans (Debt)' },
      { key: 'payables', label: 'Payables (Dues)' },
      { key: 'marketplaceChannels', label: 'Marketplace Channels' },
      { key: 'marketplaceSettlements', label: 'Marketplace Settlements' },
      { key: 'ledger', label: 'Ledger' },
      { key: 'fundingSources', label: 'Funding Sources' },
      { key: 'complianceOverview', label: 'Compliance · Overview' },
      { key: 'complianceReports', label: 'Compliance · Reports' },
    ],
  },
  { module: MODULES.RETURNS, label: 'Returns', to: '/returns', icon: Undo2 },
  {
    module: MODULES.NOTIFICATIONS,
    label: 'Notifications',
    to: '/notifications',
    icon: Bell,
    children: [
      { key: 'notifications', label: 'Notifications' },
      { key: 'communicationLogs', label: 'Communication Logs' },
    ],
  },
  {
    module: MODULES.REPORTS,
    label: 'Reports',
    to: '/reports',
    icon: FileBarChart,
    children: [
      { key: 'overview', label: 'Overview' },
      { key: 'sales', label: 'Sales' },
      { key: 'purchase', label: 'Purchase' },
      { key: 'inventory', label: 'Inventory' },
      { key: 'production', label: 'Production' },
      { key: 'finance', label: 'Finance' },
      { key: 'customer', label: 'Customer' },
      { key: 'vendor', label: 'Vendor' },
      { key: 'employee', label: 'Employee' },
    ],
  },
  {
    module: MODULES.USERS,
    label: 'Employees',
    to: '/users',
    icon: Users,
    children: [
      { key: 'users', label: 'Employees' },
      { key: 'departments', label: 'Departments' },
      { key: 'designations', label: 'Designations' },
      { key: 'company', label: 'Company' },
      { key: 'branches', label: 'Branches' },
      { key: 'warehouses', label: 'Warehouses' },
      { key: 'leaves', label: 'Leave' },
      { key: 'assets', label: 'Assets' },
      { key: 'audit-logs', label: 'Audit Logs' },
      { key: 'roles', label: 'Roles & Permissions' },
    ],
  },
];
