import { z } from 'zod';
import { ROLES } from '@/constants/roles';
import { EMPLOYMENT_STATUS } from '@/constants/statusEnums';

export const userSchema = z.object({
  firstName: z.string().min(1, 'First name is required'),
  middleName: z.string().optional(),
  lastName: z.string().min(1, 'Last name is required'),
  phone: z.string().min(10, 'Enter a valid phone number'),
  email: z.string().email('Enter a valid email').optional().or(z.literal('')),
  primaryRole: z.enum(Object.values(ROLES)).default('EMPLOYEE'),
  additionalRoles: z.array(z.enum(Object.values(ROLES))).default([]),
  departmentId: z.string().optional(),
  designationId: z.string().optional(),
  branchId: z.string().optional(),
  warehouseId: z.string().optional(),
  reportingManagerId: z.string().optional(),
  joiningDate: z.string().optional(),
  employmentStatus: z.enum(Object.values(EMPLOYMENT_STATUS)).default('probation'),
  dob: z.string().optional(),
  gender: z.string().optional(),
  bloodGroup: z.string().optional(),
  maritalStatus: z.string().optional(),
  nationality: z.string().optional(),
  passportNumber: z.string().optional(),
  drivingLicense: z.string().optional(),
  emergencyContactName: z.string().optional(),
  emergencyContactNumber: z.string().optional(),
  aadhaarNumber: z.string().optional(),
  panNumber: z.string().optional(),
  bankName: z.string().optional(),
  accountHolderName: z.string().optional(),
  bankAccount: z.string().optional(),
  ifsc: z.string().optional(),
  upiId: z.string().optional(),
  salaryStructure: z.string().optional(),
  permanentAddress: z.string().optional(),
  currentAddress: z.string().optional(),
  city: z.string().optional(),
  state: z.string().optional(),
  country: z.string().optional(),
  postalCode: z.string().optional(),
  emailNotifications: z.boolean().default(true),
  smsNotifications: z.boolean().default(true),
  inAppNotifications: z.boolean().default(true),
});
