import { createCrudApi } from '@/services/api/createCrudApi';
import { generateEmployeeCode, generateTempPassword } from '@/utils/generateEmployeeCode';
import { addNotification } from '@/services/notification.api';
import { addAuditLog } from '@/services/auditLog.api';
import { getEmployeeFullName } from '@/utils/employeeName';

const MOCK_USERS = [
  {
    id: '1',
    employeeCode: 'EMP-0001',
    firstName: 'Ronak',
    middleName: '',
    lastName: 'Singh',
    phone: '9000000001',
    email: 'ronak@meratractor.com',
    tempPassword: '123456',
    primaryRole: 'SUPER_ADMIN',
    additionalRoles: [],
    departmentId: '1',
    designationId: '1',
    branchId: '1',
    warehouseId: '1',
    reportingManagerId: '',
    joiningDate: '2024-01-01',
    employmentStatus: 'active',
    dob: '1985-04-12',
    gender: 'male',
    bloodGroup: 'O+',
    maritalStatus: 'married',
    nationality: 'Indian',
    passportNumber: '',
    drivingLicense: '',
    emergencyContactName: '',
    emergencyContactNumber: '',
    photo: null,
    aadhaarNumber: '',
    panNumber: '',
    bankAccount: '',
    ifsc: '',
    salaryStructure: '',
    address: '',
    emailNotifications: true,
    smsNotifications: true,
    inAppNotifications: true,
    documents: {},
    lastLogin: null,
  },
  {
    id: '2',
    employeeCode: 'EMP-0002',
    firstName: 'Aditya',
    middleName: 'Kumar',
    lastName: 'Singh',
    phone: '9000000002',
    email: 'aditya@dsfootwear.com',
    tempPassword: '123456',
    primaryRole: 'OWNER',
    additionalRoles: [],
    departmentId: '1',
    designationId: '2',
    branchId: '1',
    warehouseId: '1',
    reportingManagerId: '1',
    joiningDate: '2024-02-01',
    employmentStatus: 'active',
    dob: '1988-09-21',
    gender: 'male',
    bloodGroup: 'B+',
    maritalStatus: 'married',
    nationality: 'Indian',
    passportNumber: '',
    drivingLicense: '',
    emergencyContactName: '',
    emergencyContactNumber: '',
    photo: null,
    aadhaarNumber: '',
    panNumber: '',
    bankAccount: '',
    ifsc: '',
    salaryStructure: '',
    address: '',
    emailNotifications: true,
    smsNotifications: true,
    inAppNotifications: true,
    documents: {},
    lastLogin: null,
  },
  {
    id: '3',
    employeeCode: 'EMP-0003',
    firstName: 'Priya',
    middleName: '',
    lastName: 'Sharma',
    phone: '9000000003',
    email: 'priya@dsfootwear.com',
    tempPassword: '123456',
    primaryRole: 'SALES',
    additionalRoles: [],
    departmentId: '2',
    designationId: '3',
    branchId: '2',
    warehouseId: '2',
    reportingManagerId: '2',
    joiningDate: '2024-03-01',
    employmentStatus: 'active',
    dob: '1992-01-15',
    gender: 'female',
    bloodGroup: 'A+',
    maritalStatus: 'single',
    nationality: 'Indian',
    passportNumber: '',
    drivingLicense: '',
    emergencyContactName: '',
    emergencyContactNumber: '',
    photo: null,
    aadhaarNumber: '',
    panNumber: '',
    bankAccount: '',
    ifsc: '',
    salaryStructure: '',
    address: '',
    emailNotifications: true,
    smsNotifications: true,
    inAppNotifications: true,
    documents: {},
    lastLogin: null,
  },
  {
    id: '4',
    employeeCode: 'EMP-0004',
    firstName: 'Rahul',
    middleName: '',
    lastName: 'Verma',
    phone: '9000000004',
    email: 'rahul@dsfootwear.com',
    tempPassword: '123456',
    primaryRole: 'INVENTORY',
    additionalRoles: [],
    departmentId: '6',
    designationId: '7',
    branchId: '1',
    warehouseId: '1',
    reportingManagerId: '2',
    joiningDate: '2024-04-01',
    employmentStatus: 'terminated',
    dob: '1990-06-30',
    gender: 'male',
    bloodGroup: 'AB+',
    maritalStatus: 'married',
    nationality: 'Indian',
    passportNumber: '',
    drivingLicense: '',
    emergencyContactName: '',
    emergencyContactNumber: '',
    photo: null,
    aadhaarNumber: '',
    panNumber: '',
    bankAccount: '',
    ifsc: '',
    salaryStructure: '',
    address: '',
    emailNotifications: true,
    smsNotifications: true,
    inAppNotifications: true,
    documents: {},
    lastLogin: null,
  },
  {
    id: '5',
    employeeCode: 'EMP-0005',
    firstName: 'Vikram',
    middleName: '',
    lastName: 'Mehta',
    phone: '9000000005',
    email: 'vikram@dsfootwear.com',
    tempPassword: '123456',
    primaryRole: 'PURCHASE',
    additionalRoles: [],
    departmentId: '3',
    designationId: '4',
    branchId: '1',
    warehouseId: '1',
    reportingManagerId: '2',
    joiningDate: '2024-05-01',
    employmentStatus: 'active',
    dob: '1991-11-02',
    gender: 'male',
    bloodGroup: 'O-',
    maritalStatus: 'single',
    nationality: 'Indian',
    passportNumber: '',
    drivingLicense: '',
    emergencyContactName: '',
    emergencyContactNumber: '',
    photo: null,
    aadhaarNumber: '',
    panNumber: '',
    bankAccount: '',
    ifsc: '',
    salaryStructure: '',
    address: '',
    emailNotifications: true,
    smsNotifications: true,
    inAppNotifications: true,
    documents: {},
    lastLogin: null,
  },
  {
    id: '6',
    employeeCode: 'EMP-0006',
    firstName: 'Sanjay',
    middleName: '',
    lastName: 'Kapoor',
    phone: '9000000006',
    email: 'sanjay@dsfootwear.com',
    tempPassword: '123456',
    primaryRole: 'PRODUCTION',
    additionalRoles: ['DISPATCH'],
    departmentId: '4',
    designationId: '5',
    branchId: '1',
    warehouseId: '1',
    reportingManagerId: '2',
    joiningDate: '2024-06-01',
    employmentStatus: 'active',
    dob: '1989-03-18',
    gender: 'male',
    bloodGroup: 'B-',
    maritalStatus: 'married',
    nationality: 'Indian',
    passportNumber: '',
    drivingLicense: '',
    emergencyContactName: '',
    emergencyContactNumber: '',
    photo: null,
    aadhaarNumber: '',
    panNumber: '',
    bankAccount: '',
    ifsc: '',
    salaryStructure: '',
    address: '',
    emailNotifications: true,
    smsNotifications: true,
    inAppNotifications: true,
    documents: {},
    lastLogin: null,
  },
  {
    id: '7',
    employeeCode: 'EMP-0007',
    firstName: 'Neha',
    middleName: '',
    lastName: 'Gupta',
    phone: '9000000007',
    email: 'neha@dsfootwear.com',
    tempPassword: '123456',
    primaryRole: 'ACCOUNTANT',
    additionalRoles: [],
    departmentId: '5',
    designationId: '6',
    branchId: '1',
    warehouseId: '1',
    reportingManagerId: '2',
    joiningDate: '2024-07-01',
    employmentStatus: 'active',
    dob: '1993-07-09',
    gender: 'female',
    bloodGroup: 'A-',
    maritalStatus: 'single',
    nationality: 'Indian',
    passportNumber: '',
    drivingLicense: '',
    emergencyContactName: '',
    emergencyContactNumber: '',
    photo: null,
    aadhaarNumber: '',
    panNumber: '',
    bankAccount: '',
    ifsc: '',
    salaryStructure: '',
    address: '',
    emailNotifications: true,
    smsNotifications: true,
    inAppNotifications: true,
    documents: {},
    lastLogin: null,
  },
  {
    id: '8',
    employeeCode: 'EMP-0008',
    firstName: 'Suresh',
    middleName: '',
    lastName: 'Yadav',
    phone: '9000000008',
    email: 'suresh@dsfootwear.com',
    tempPassword: '123456',
    primaryRole: 'DISPATCH',
    additionalRoles: [],
    departmentId: '6',
    designationId: '7',
    branchId: '2',
    warehouseId: '2',
    reportingManagerId: '2',
    joiningDate: '2024-08-01',
    employmentStatus: 'active',
    dob: '1994-12-25',
    gender: 'male',
    bloodGroup: 'O+',
    maritalStatus: 'single',
    nationality: 'Indian',
    passportNumber: '',
    drivingLicense: '',
    emergencyContactName: '',
    emergencyContactNumber: '',
    photo: null,
    aadhaarNumber: '',
    panNumber: '',
    bankAccount: '',
    ifsc: '',
    salaryStructure: '',
    address: '',
    emailNotifications: true,
    smsNotifications: true,
    inAppNotifications: true,
    documents: {},
    lastLogin: null,
  },
];

export function findEmployeeByPhone(phone) {
  return MOCK_USERS.find((employee) => employee.phone === phone);
}

/**
 * Employee Create Flow (plan.md Chapter 9): once department/designation/role
 * are assigned, generate the employee code and a temporary password, then
 * "send" it — simulated here as a notification since there's no SMS gateway.
 */
function onboardEmployee(record) {
  const employeeCode = generateEmployeeCode(MOCK_USERS);
  const tempPassword = generateTempPassword();
  const next = { ...record, employeeCode, tempPassword };

  addNotification({
    title: 'Employee onboarded',
    message: `SMS sent to ${next.phone}: Welcome ${getEmployeeFullName(next)}, your employee code is ${employeeCode} and temporary password is ${tempPassword}.`,
  });

  addAuditLog({
    employeeId: next.id,
    action: 'employee_created',
    description: `${getEmployeeFullName(next)} onboarded as ${employeeCode}`,
  });

  return next;
}

export const userApi = createCrudApi('users', MOCK_USERS, {
  statusField: 'employmentStatus',
  hooks: { afterCreate: onboardEmployee },
});
