import { createCrudApi } from '@/services/api/createCrudApi';

const MOCK_VENDORS = [
  {
    id: '1',
    name: 'Leo Leathers',
    vendorType: 'raw_material',
    phone: '9822200001',
    email: 'sales@leoleathers.example',
    address: 'Kanpur, UP',
    gstNumber: '09AABCL1234K1Z9',
    paymentTerms: 'Net 30',
    creditLimit: 400000,
    creditDays: 30,
    addresses: [
      { type: 'registered_office', contactPerson: 'Leo Sales Desk', phone: '9822200001', addressLine: 'Leather Market', city: 'Kanpur', state: 'Uttar Pradesh', country: 'India', postalCode: '208001' },
    ],
    qualityRating: 4,
    status: 'active',
  },
  {
    id: '2',
    name: 'Sole Components Pvt Ltd',
    vendorType: 'raw_material',
    phone: '9822200002',
    email: 'orders@solecomponents.example',
    address: 'Agra, UP',
    gstNumber: '09AABCS5678L1Z7',
    paymentTerms: 'Net 15',
    creditLimit: 250000,
    creditDays: 15,
    addresses: [],
    qualityRating: 4,
    status: 'active',
  },
  {
    id: '3',
    name: 'Metro Packaging Co',
    vendorType: 'packaging',
    phone: '9822200003',
    email: 'sales@metropackaging.example',
    address: 'Delhi',
    gstNumber: '07AABCM9012M1Z5',
    paymentTerms: 'Net 15',
    creditLimit: 150000,
    creditDays: 15,
    addresses: [],
    qualityRating: 4,
    status: 'active',
  },
  {
    id: '4',
    name: 'Apex Textile Mills',
    vendorType: 'raw_material',
    phone: '9822200004',
    email: 'sales@apextextiles.example',
    address: 'Panipat, Haryana',
    gstNumber: '06AABCA3456N1Z3',
    paymentTerms: 'Net 30',
    creditLimit: 200000,
    creditDays: 30,
    addresses: [],
    qualityRating: 4,
    status: 'active',
  },
];

export const vendorApi = createCrudApi('vendors', MOCK_VENDORS);
