/**
 * ERP Roles (plan.md Chapter 2, RBAC UI Engine) — department-scoped roles
 * instead of generic tiers, so each role maps to the module its own
 * department works in.
 */
export const ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  OWNER: 'OWNER',
  ACCOUNTANT: 'ACCOUNTANT',
  CA: 'CA',
  PURCHASE: 'PURCHASE',
  INVENTORY: 'INVENTORY',
  PRODUCTION: 'PRODUCTION',
  SALES: 'SALES',
  DISPATCH: 'DISPATCH',
  CUSTOMER_SUPPORT: 'CUSTOMER_SUPPORT',
  EMPLOYEE: 'EMPLOYEE',
};

export const ACTIONS = {
  VIEW: 'view',
  CREATE: 'create',
  EDIT: 'edit',
  DELETE: 'delete',
};

const ALL_ACTIONS = Object.values(ACTIONS);
const READ_ONLY = [ACTIONS.VIEW];
const NO_DELETE = [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.EDIT];
const NONE = [];

export const MODULES = {
  DASHBOARD: 'dashboard',
  USERS: 'users',
  PRODUCTS: 'products',
  PURCHASES: 'purchases',
  INVENTORY: 'inventory',
  PRODUCTION: 'production',
  SALES: 'sales',
  FINANCE: 'finance',
  RETURNS: 'returns',
  NOTIFICATIONS: 'notifications',
  REPORTS: 'reports',
};

/**
 * Module -> allowed actions per role. SUPER_ADMIN and OWNER get full access
 * by default (see hasPermission); every other role only sees its own
 * department's module edited, and everything else read-only or hidden.
 */
export const ROLE_PERMISSIONS = {
  [ROLES.ACCOUNTANT]: {
    [MODULES.DASHBOARD]: READ_ONLY,
    [MODULES.USERS]: NONE,
    [MODULES.PRODUCTS]: READ_ONLY,
    [MODULES.PURCHASES]: READ_ONLY,
    [MODULES.INVENTORY]: NONE,
    [MODULES.PRODUCTION]: NONE,
    [MODULES.SALES]: READ_ONLY,
    [MODULES.FINANCE]: NO_DELETE,
    [MODULES.RETURNS]: READ_ONLY,
    [MODULES.NOTIFICATIONS]: READ_ONLY,
    [MODULES.REPORTS]: READ_ONLY,
  },
  [ROLES.CA]: {
    [MODULES.DASHBOARD]: READ_ONLY,
    [MODULES.USERS]: NONE,
    [MODULES.PRODUCTS]: NONE,
    [MODULES.PURCHASES]: READ_ONLY,
    [MODULES.INVENTORY]: NONE,
    [MODULES.PRODUCTION]: NONE,
    [MODULES.SALES]: READ_ONLY,
    [MODULES.FINANCE]: READ_ONLY,
    [MODULES.RETURNS]: NONE,
    [MODULES.NOTIFICATIONS]: READ_ONLY,
    [MODULES.REPORTS]: READ_ONLY,
  },
  [ROLES.PURCHASE]: {
    [MODULES.DASHBOARD]: READ_ONLY,
    [MODULES.USERS]: NONE,
    [MODULES.PRODUCTS]: READ_ONLY,
    [MODULES.PURCHASES]: NO_DELETE,
    [MODULES.INVENTORY]: READ_ONLY,
    [MODULES.PRODUCTION]: NONE,
    [MODULES.SALES]: NONE,
    [MODULES.FINANCE]: NONE,
    [MODULES.RETURNS]: NONE,
    [MODULES.NOTIFICATIONS]: READ_ONLY,
    [MODULES.REPORTS]: READ_ONLY,
  },
  [ROLES.INVENTORY]: {
    [MODULES.DASHBOARD]: READ_ONLY,
    [MODULES.USERS]: NONE,
    [MODULES.PRODUCTS]: READ_ONLY,
    [MODULES.PURCHASES]: READ_ONLY,
    [MODULES.INVENTORY]: NO_DELETE,
    [MODULES.PRODUCTION]: READ_ONLY,
    [MODULES.SALES]: NONE,
    [MODULES.FINANCE]: NONE,
    [MODULES.RETURNS]: NO_DELETE,
    [MODULES.NOTIFICATIONS]: READ_ONLY,
    [MODULES.REPORTS]: READ_ONLY,
  },
  [ROLES.PRODUCTION]: {
    [MODULES.DASHBOARD]: READ_ONLY,
    [MODULES.USERS]: NONE,
    [MODULES.PRODUCTS]: READ_ONLY,
    [MODULES.PURCHASES]: READ_ONLY,
    [MODULES.INVENTORY]: READ_ONLY,
    [MODULES.PRODUCTION]: NO_DELETE,
    [MODULES.SALES]: NONE,
    [MODULES.FINANCE]: NONE,
    [MODULES.RETURNS]: NONE,
    [MODULES.NOTIFICATIONS]: READ_ONLY,
    [MODULES.REPORTS]: READ_ONLY,
  },
  [ROLES.SALES]: {
    [MODULES.DASHBOARD]: READ_ONLY,
    [MODULES.USERS]: NONE,
    [MODULES.PRODUCTS]: READ_ONLY,
    [MODULES.PURCHASES]: NONE,
    [MODULES.INVENTORY]: READ_ONLY,
    [MODULES.PRODUCTION]: NONE,
    [MODULES.SALES]: NO_DELETE,
    [MODULES.FINANCE]: NONE,
    [MODULES.RETURNS]: NO_DELETE,
    [MODULES.NOTIFICATIONS]: READ_ONLY,
    [MODULES.REPORTS]: READ_ONLY,
  },
  [ROLES.DISPATCH]: {
    [MODULES.DASHBOARD]: READ_ONLY,
    [MODULES.USERS]: NONE,
    [MODULES.PRODUCTS]: NONE,
    [MODULES.PURCHASES]: NONE,
    [MODULES.INVENTORY]: READ_ONLY,
    [MODULES.PRODUCTION]: NONE,
    [MODULES.SALES]: READ_ONLY,
    [MODULES.FINANCE]: NONE,
    [MODULES.RETURNS]: NO_DELETE,
    [MODULES.NOTIFICATIONS]: READ_ONLY,
    [MODULES.REPORTS]: NONE,
  },
  [ROLES.CUSTOMER_SUPPORT]: {
    [MODULES.DASHBOARD]: READ_ONLY,
    [MODULES.USERS]: NONE,
    [MODULES.PRODUCTS]: READ_ONLY,
    [MODULES.PURCHASES]: NONE,
    [MODULES.INVENTORY]: NONE,
    [MODULES.PRODUCTION]: NONE,
    [MODULES.SALES]: READ_ONLY,
    [MODULES.FINANCE]: NONE,
    [MODULES.RETURNS]: NO_DELETE,
    [MODULES.NOTIFICATIONS]: ALL_ACTIONS,
    [MODULES.REPORTS]: NONE,
  },
  [ROLES.EMPLOYEE]: {
    [MODULES.DASHBOARD]: READ_ONLY,
    [MODULES.USERS]: NONE,
    [MODULES.PRODUCTS]: READ_ONLY,
    [MODULES.PURCHASES]: READ_ONLY,
    [MODULES.INVENTORY]: READ_ONLY,
    [MODULES.PRODUCTION]: READ_ONLY,
    [MODULES.SALES]: READ_ONLY,
    [MODULES.FINANCE]: NONE,
    [MODULES.RETURNS]: READ_ONLY,
    [MODULES.NOTIFICATIONS]: READ_ONLY,
    [MODULES.REPORTS]: READ_ONLY,
  },
};

export const FULL_ACCESS_ROLES = [ROLES.SUPER_ADMIN, ROLES.OWNER];

export function hasPermission(role, module, action = ACTIONS.VIEW, permissions = ROLE_PERMISSIONS) {
  if (!role) return false;
  if (FULL_ACCESS_ROLES.includes(role)) return true;
  const modulePermissions = permissions[role]?.[module] ?? [];
  return modulePermissions.includes(action);
}
