function resourceKeys(name) {
  return {
    all: [name],
    list: (filters) => [name, 'list', filters],
    detail: (id) => [name, 'detail', id],
  };
}

export const queryKeys = {
  auth: { me: ['auth', 'me'] },
  users: resourceKeys('users'),
  departments: resourceKeys('departments'),
  designations: resourceKeys('designations'),
  categories: resourceKeys('categories'),
  productVariants: resourceKeys('productVariants'),
  customers: resourceKeys('customers'),
  vendors: resourceKeys('vendors'),
  branches: resourceKeys('branches'),
  roles: resourceKeys('roles'),
  warehouses: resourceKeys('warehouses'),
  company: resourceKeys('company'),
  brands: resourceKeys('brands'),
  loginHistory: resourceKeys('loginHistory'),
  attendance: resourceKeys('attendance'),
  leaves: resourceKeys('leaves'),
  assets: resourceKeys('assets'),
  auditLogs: resourceKeys('auditLogs'),
  products: resourceKeys('products'),
  purchases: resourceKeys('purchases'),
  inventory: resourceKeys('inventory'),
  production: resourceKeys('production'),
  materialIssueRequests: resourceKeys('materialIssueRequests'),
  bom: resourceKeys('bom'),
  machines: resourceKeys('machines'),
  approvalRequests: resourceKeys('approvalRequests'),
  sales: resourceKeys('sales'),
  finance: resourceKeys('finance'),
  returns: resourceKeys('returns'),
  warehouseZones: resourceKeys('warehouseZones'),
  racks: resourceKeys('racks'),
  shelves: resourceKeys('shelves'),
  bins: resourceKeys('bins'),
  inventoryMovements: resourceKeys('inventoryMovements'),
  purchaseRequests: resourceKeys('purchaseRequests'),
  rfqs: resourceKeys('rfqs'),
  vendorQuotations: resourceKeys('vendorQuotations'),
  goodsReceiptNotes: resourceKeys('goodsReceiptNotes'),
  payments: resourceKeys('payments'),
  vendorBills: resourceKeys('vendorBills'),
  creditNotes: resourceKeys('creditNotes'),
  ledger: resourceKeys('ledger'),
  loans: resourceKeys('loans'),
  gstProfile: { all: ['gstProfile'] },
  statutoryAudits: resourceKeys('statutoryAudits'),
  financeReports: {
    gstr1: (range) => ['financeReports', 'gstr1', range],
    gstr3b: (range) => ['financeReports', 'gstr3b', range],
    gstr2bProxy: (range) => ['financeReports', 'gstr2bProxy', range],
    pnl: (range) => ['financeReports', 'pnl', range],
  },
  customerCommunications: resourceKeys('customerCommunications'),
  qualityInspections: resourceKeys('qualityInspections'),
  loanEsignRequests: resourceKeys('loanEsignRequests'),
  notifications: resourceKeys('notifications'),
  communicationLogs: resourceKeys('communicationLogs'),
  reports: resourceKeys('reports'),
  dashboard: { all: ['dashboard'] },
  settings: { all: ['settings'] },
  fundingSources: resourceKeys('fundingSources'),
  documents: resourceKeys('documents'),
  itemCategories: resourceKeys('itemCategories'),
  items: resourceKeys('items'),
  itemStock: resourceKeys('itemStock'),
  itemStockMovements: resourceKeys('itemStockMovements'),
  fixedAssets: resourceKeys('fixedAssets'),
  fixedAssetMaintenance: resourceKeys('fixedAssetMaintenance'),
};
